- name: Install npm
  apt: name=npm  state=present
          
- name: Copy Feature_1 Code 
  copy: src=../code/. dest=/var/www/{{ http_host1 }}

- name: Start Application
  command: chdir=/var/www/{{ http_host1 }}  npm install --production
  notify: 
   - Restart Apache
