- name: Install nodejs 
  apt: name=npm  state=present
          
- name: Copy Feature_1 Code 
  command: cp -r ../code/ /var/www/{{ http_host1 }}

- name: Start Application
  command: chdir=/var/www/{{ http_host1 }}  npm install --production
  notify: 
   - Reload Apache
